name: Activate Dynatrace Gateway

on: workflow_dispatch

env:
  zone: us-central1-c
  releaseName: datadog-agent  

jobs:
 GCP-start-gateway:
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        #version: '290.0.1'
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true
    - run: gcloud compute instances start dt-gateway --zone=${{ env.zone }}
