# This is a basic workflow to help you get started with Actions

name: Datadog Install

on: workflow_dispatch

env:
  zone: us-central1-c
  releaseName: datadog-agent 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 Install-DD:
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        #version: '290.0.1'
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true
    # Get new cluster credentials 
    - run: |-
        gcloud container clusters get-credentials ${{secrets.GKE_CLUSTER_NAME}} --zone=${{ env.zone }}
    # Set up DataDog in Kubernetes cluster
    - run: |-
        helm repo add datadog https://helm.datadoghq.com
        helm repo add stable https://charts.helm.sh/stable
        helm repo update
        helm install ${{ env.releaseName }} -f datadog/values.yaml  --set datadog.apiKey=${{ secrets.DATADOG_API_KEY }} datadog/datadog --set targetSystem=linux
