# This is a basic workflow to help you get started with Actions
name: Deactivate Dynatrace Gateway

on: workflow_dispatch

env:
  zone: us-central1-c

jobs:
 GCP-Deactivate-Gateway:
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        #version: '290.0.1'
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true
    - run: gcloud compute instances stop dt-gateway --zone=${{ env.zone }}
